### ISSUE TITLE
Request :android camera

### ISSUE THREAD

**Issue by Kiozak** [dahjelle/react-native-android-webview-file-image-upload#1]
Hello ,

Your project saved my life , thank you for your help ^^,
i would love if you can add the camera access too 

Thanks

**Comment by dahjelle** [comment]
I thought the Android camera was working with this…but it's been a while, and likely only works on certain Android versions. :-)

I hadn't written any Android code before this, and was able to find quite a few answers just by Googling around. If there are changes necessary, I expect most of them would be in [this method](https://github.com/dahjelle/react-native-android-webview-file-image-upload/blob/master/android/app/src/main/java/com/webviewtest/CustomWebViewManager.java#L27) or [this method](https://github.com/dahjelle/react-native-android-webview-file-image-upload/blob/master/android/app/src/main/java/com/webviewtest/CustomWebViewModule.java#L65). I'd be happy to accept a PR if you have one!

Have a great day!
