### ISSUE TITLE
prevent android modal from closing on outside touch

### ISSUE THREAD

**Issue by juniusfadli** [dahjelle/react-native-android-webview-file-image-upload#2]
i tried to add alertdialog.builder setcanceledontouchoutside inside CustomWebViewModule.java but i got error: can't find symbol.

i want to disable dismiss modal when user touch outside.

**Comment by dahjelle** [comment]
I'm afraid I know just enough Java to have pulled together this repo from several other people's examples…which means I don't have much hope of helping.

Perhaps StackOverflow can?

- https://stackoverflow.com/questions/8086189/what-causes-cant-find-symbol-and-how-to-fix-it#8086225
- https://www.thoughtco.com/error-message-cannot-find-symbol-2034060
- https://stackoverflow.com/questions/5037992/java-cant-find-symbol

A missing `import`, maybe?

**Comment by loiclouvet** [comment]
Hey there, someone found a solution ?

**Comment by zbbjzh** [comment]
builder.setCancelable(false);

**Comment by dahjelle** [comment]
I'm going to deprecate this repo; it looks like [react-native-webview]() added Android file upload support as of [v2.10.0](https://github.com/react-native-community/react-native-webview/releases/tag/v2.10.0). While I haven't tested it, it is much more likely to be maintained.
