### ISSUE TITLE
When you hit the back button, you can't click it again

### ISSUE THREAD

**Issue by LiuduZero** [dahjelle/react-native-android-webview-file-image-upload#4]
Click the input file and the dialog will be displayed, then press the return button of the phone, and then click the input and the dialog will not be displayed

**Comment by dahjelle** [comment]
I haven't worked on this project for some time; I'd recommend using https://github.com/react-native-community/react-native-webview instead. (I haven't used it myself, yet, but I see they have added Android file upload support [as of v2.10.0](https://github.com/react-native-community/react-native-webview/releases/tag/v2.10.0).) I'll add a deprecation notice to this repo now.
